nelmio_api_doc:
    documentation:
        info:
            title: "API Portfolio"
            description: "une api pour gérer les projets et apprndre à construire des apis"
            version: "1.0.0"
    areas: # to filter documented areas
        path_patterns:
            - ^/api # Accepts routes under /api except /api/doc
